definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  handler.sendMessageReq:
    properties:
      content:
        type: string
    type: object
  handler.sendMessageRes:
    properties:
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /messages/process:
    put:
      description: Trigger the processing of messages
      responses:
        "200":
          description: Successfully processed messages
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Process messages
      tags:
      - messages
  /messages/send:
    post:
      consumes:
      - application/json
      description: Send a message to the service
      parameters:
      - description: Message Content
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handler.sendMessageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.sendMessageRes'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Send a message
      tags:
      - messages
swagger: "2.0"
